# fail2ban filter for LACMP Panel failed logins.
# logpath is set in jail.d/lacmp-panel.conf
[Definition]
failregex = LACMP_PANEL_AUTH_FAIL ip=<HOST>
ignoreregex =
datepattern = ^%%Y-%%m-%%dT%%H:%%M:%%SZ
