# fail2ban filter for LCMP Panel failed logins.
# logpath is set in jail.d/lcmp-panel.conf
[Definition]
failregex = LCMP_PANEL_AUTH_FAIL ip=<HOST>
ignoreregex =
datepattern = ^%%Y-%%m-%%dT%%H:%%M:%%SZ
